Program
..FuncDefinition
....Int
....Id(main)
....ParamList
......ParamDeclaration
........Void
....FuncBody
......Declaration
........Char
........Id(i)
........ChrLit('A')
......While
........Le
..........Id(i)
..........ChrLit('Z')
........StatList
..........Call
............Id(putchar)
............Id(i)
..........Store
............Id(i)
............Add
..............Id(i)
..............IntLit(1)
......Return
........IntLit(0)
